WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_TITLE = "Covid19"
MOVEMENT_SPEED = 5

BULLET_SPEED = 10
BULLETS_GAP = 10

VIRUS_SPEED = 6
BLOODCLOT_SPEED = 3
BLOODCLOT_GROWTH_RATE = 0.03
BLOODCLOT_SCALE_MIN = 0.75
BLOODCLOT_SCALE_MAX = 3.25

SPRITE_SCALING = 0.5
TEXTURE_LEFT = 0
TEXTURE_RIGHT = 1

LIVES = 3
HIT_VALUE = 10