WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_TITLE = "Covid19"
MOVEMENT_SPEED = 5
BULLET_SPEED = 10
VIRUS_SPEED = 6
BLOODCLOT_SPEED = 3
ENLARGED_BLOODCLOT_SCALE = 1.5

SPRITE_SCALING = 0.5
TEXTURE_LEFT = 0
TEXTURE_RIGHT = 1

LIVES = 3
HIT_VALUE = 10